workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      flutter: 3.19.2
      android_signing: 
        - codemagic-healify
      vars: 
        GITHUB_TOKEN  


    triggering:
      events:
        - tag
      branch_patterns:
        - pattern : '*'
          include: true
          source : true

    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Build AAB with Flutter
        script: | 
          flutter build apk --release
      - name: Publish to Github
        script: | 
         if [ -z ${CM_TAG} ]; then
           echo "Not a tag build, will not publish GitHub release"
           exit 0
         fi

         gh release create "${CM_TAG}" \
           --title "Healify ${CM_TAG}" \
           --notes-file changelog.md \
           android/build/app/outputs.apk/release/app-arm64-v8a-release.apk

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log      

    publishing: 
      email:
        recipients:
          - deepanshu.r.sharma@gmail.com
        notify:
          success: true
          failure: false