// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjz9jex2ZHhA8vYhBcUGKStAzbh55sZYo',
    appId: '1:63396486325:web:4d593fba3182d2ecfcf2fc',
    messagingSenderId: '63396486325',
    projectId: 'healify-66f8c',
    authDomain: 'healify-66f8c.firebaseapp.com',
    storageBucket: 'healify-66f8c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjGHV7wrTP3ChslsuLsBXiaQHjwkBAECg',
    appId: '1:63396486325:android:31bbb282428f9fb2fcf2fc',
    messagingSenderId: '63396486325',
    projectId: 'healify-66f8c',
    storageBucket: 'healify-66f8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTS_WyYMprlrVcAnVktyUKLytaYVarfhI',
    appId: '1:63396486325:ios:f835f0973b21c631fcf2fc',
    messagingSenderId: '63396486325',
    projectId: 'healify-66f8c',
    storageBucket: 'healify-66f8c.appspot.com',
    iosBundleId: 'com.example.healify',
  );

}